// This is an autogenerated file from Firebase Studio.
import { initializeApp, getApps } from "firebase/app";

const firebaseConfig = {
  apiKey: "AIzaSyA28su7z5iSfO8Dqw30IPn3KpP7ShDvILU",
  authDomain: "kjsomiya-30e78.firebaseapp.com",
  databaseURL: "https://kjsomiya-30e78-default-rtdb.firebaseio.com",
  projectId: "kjsomiya-30e78",
  storageBucket: "kjsomiya-30e78.firebasestorage.app",
  messagingSenderId: "1083715252948",
  appId: "1:1083715252948:web:05b5efcd43f0b94539c141",
  measurementId: "G-P2C9Q4PKM5"
};

// Initialize Firebase
import type { FirebaseApp } from 'firebase/app';

let app: FirebaseApp;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApps()[0];
}

export { app };
